server:
  port: 8093
  servlet:
    context-path: /applets
sqlServerVersion:
  sqlserver2005
spring:
  datasource:
    dynamic:
      primary: read #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        read:
          url: jdbc:sqlserver://localhost:1433;DatabaseName=Cguan20190703
          username: sa
          password: Qwe123456
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver # 3.2.0开始支持SPI可省略此配置
        write:
          url: jdbc:sqlserver://localhost:1433;DatabaseName=Cguan20210814
          username: sa
          password: Qwe123456
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
